### PR TITLE
fix Secret/secretmanager.aws custom diff logic when replica config is empty

### LINKED ISSUE #1128: [Bug]: Secret never Sync
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Resource(s)

secretsmanager.aws.upbound.io/v1beta1 - Secret

### Resource MRs required to reproduce the bug

```
apiVersion: secretsmanager.aws.upbound.io/v1beta1
kind: Secret
metadata:
  name: test-dmaganto1
spec:
  forProvider:
    name: test-dmaganto1
    region: eu-central-1
    recoveryWindowInDays: 0
  providerConfigRef:
    name: aws-admin-my-account-upbound
```

### Steps to Reproduce

Apply this resource in the cluster

### What happened?

It never reach the state Sync: true

### Relevant Error Output Snippet

```shell
- lastTransitionTime: "2024-02-06T10:12:27Z"
    message: 'observe failed: cannot compute the instance diff: failed to compute
      the customized terraform.InstanceDiff: could not read replica block from config'
```

### Crossplane Version

1.14.5

### Provider Version

1.0.0

### Kubernetes Version

v1.28.2

### Kubernetes Distribution

EKS

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by erhancagirici**
### Description of your changes

Fixes the custom diff logic (introduced at https://github.com/upbound/provider-aws/pull/1107) for `replica` attribute when it is not specified in the config and the diff does not involve `replica` field. The custom diff function is triggered for any update diff, and the current logic tries to read the `replica` field unconditionally. When `replica` is not specified in config, the get operation fails the whole custom diff function, therefore the Observe operation.

This change fixes the custom diff logic by: 
- early exit with no error when there is no change/diff involved for `replica`. We only need to change
- early exit with no error if `replica` attibute is not specified in the MR spec. This is already handled properly by the regular diff and needs no customization.
 
Fixes #1128 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested with the spec at #1128

### CODE REVIEW

**Comment by mbbush** [comment]
/test-examples="examples/secretsmanager/v1beta1/secret.yaml"

**Comment by mbbush** [comment]
@erhancagirici this looks like a good fix, but in the interest of improving our test coverage, I'm puzzled why uptest doesn't fail on `main` without this fix. 

When I tried to reproduce the issue, I got the error described in #1128 when I was observing an existing secret, by setting the external name annotation, but not when I just created a new secret. It seems like that _should_ be caught by the import step in uptest, yet that passes consistently for me. 

Any ideas why?

**Comment by mbbush** [comment]
It looks like the key difference in reproducing this bug is that when I duplicated the existing resource, I changed its metadata.name, which changed one of the crossplane-managed tags, which created a non-nil diff. 

This makes me want to get Update tests actually running in uptest for provider-aws.

File: config/secretsmanager/config.go [hunk 1]
```diff
@@ -35,13 +35,25 @@ func Configure(p *config.Provider) { //nolint:gocyclo
 				return diff, nil
 			}
 
+			resData, err := schema.InternalMap(r.TerraformResource.SchemaMap()).Data(state, diff)
+			if err != nil {
+				return nil, errors.New("could not construct resource data")
```
Comment (mbbush) [inline config/secretsmanager/config.go:40]: Is this really something we want to fail the whole observe loop for? I don't fully understand when this could happen, so I don't know how bad it is.

**Review by mbbush — COMMENTED** [review]
I was able to reproduce the bug using uptest, and opened #1154 with examples that fail on main, but pass on this branch. 

I'd be happy for you to just cherry-pick/copy in that commit to your branch, or merge my PR and rebase, or whatever other git workflow you find easiest.

File: config/secretsmanager/config.go (hunk 1 above)
Comment (erhancagirici) [reply config/secretsmanager/config.go:40]: under "normal" operation this should never return an error. An error here indicates an issue with the resource schema or the produced state. More specifically, this is a very fundamental operation and the same line is also run by the terraform SDK library already in earlier stages of observe, so any error should be already emitted if any before visiting the custom diff function.So, IMHO it is OK to fail the whole observe here

**Comment by erhancagirici** [comment]
> I was able to reproduce the bug using uptest, and opened #1154 with examples that fail on main, but pass on this branch.
> 
> I'd be happy for you to just cherry-pick/copy in that commit to your branch, or merge my PR and rebase, or whatever other git workflow you find easiest.

Many thanks 🎉  
As you have already discovered, this bug is reproducible when 
- a non-nil Update diff occurs (non-create, non-destroy)
- `replica` is not specified in resource config

I was also just about to send a very similar example change, and for the sake of completeness of this PR, I will cherrypick your commit here. Thanks again for the valuable contribution!

**Comment by erhancagirici** [comment]
/test-examples="examples/secretsmanager/v1beta1/secret.yaml"

**Comment by erhancagirici** [comment]
/test-examples="examples/secretsmanager/v1beta1/secret-withreplica.yaml"

**Review by sergenyalcin — APPROVED** [review]
Thanks @erhancagirici LGTM!
