### PR TITLE
Fix late init of SecurityGroupRule with `self: true`

### LINKED ISSUE #228: ec2: `SecurityGroupRule` is not working when `spec.forProvider.self` is set to `true`
### What happened?

When `spec.forProvider.self` is set to `true` we hit 

```
  Warning  CannotObserveExternalResource    1s (x3 over 3s)    managed/ec2.aws.upbound.io/v1beta1, kind=securitygrouprule  cannot run refresh: refresh failed: Conflicting configuration arguments: "self": conflicts with source_security_group_id
```

### How can we reproduce it?

```
cat example.yaml
apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: sample-vpc
spec:
  forProvider:
    cidrBlock: 172.16.0.0/16
    region: us-east-1
    tags:
      Name: DemoVpc

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  labels:
    selector: here-i-am
  name: test-vpc
spec:
  deletionPolicy: Delete
  forProvider:
    region: us-east-1
    vpcIdRef:
      name: sample-vpc

---

apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: test-vpc-securitygroup
spec:
  deletionPolicy: Delete
  forProvider:
    fromPort: 22
    protocol: tcp
    region: us-east-1
    securityGroupIdSelector:
      matchLabels:
        selector: here-i-am
    self: true
    toPort: 22
    type: ingress
```

```
kubectl apply -f example.yaml
```

```
kubectl describe securitygrouprule.ec2.aws.upbound.io/test-vpc-securitygroup
....
  Warning  CannotObserveExternalResource    84s (x4 over 102s)     managed/ec2.aws.upbound.io/v1beta1, kind=securitygrouprule  cannot run refresh: refresh failed: Conflicting configuration arguments: "source_security_group_id": conflicts with self
Conflicting configuration arguments: "self": conflicts with source_security_group_id
```

### What environment did it happen in?

* Universal Crossplane Version: universal-crossplane-1.9.1-up.2
* Provider Version: xpkg.upbound.io/upbound/provider-aws:v0.21.0

### PR DESCRIPTION
**Pull request by ytsarev**
### Description of your changes

Add late init to `self` and `source_security_group_id`

Fixes #228

Signed-off-by: Yury Tsarev <yury@upbound.io>

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

```
k apply -f examples/ec2/securitygrouprule-self-true.yaml
```

```
k get managed
NAME                                        READY   SYNCED   EXTERNAL-NAME          AGE
securitygroup.ec2.aws.upbound.io/test-vpc   True    True     sg-00c2b14d55b3da787   10m

NAME                                READY   SYNCED   EXTERNAL-NAME           AGE
vpc.ec2.aws.upbound.io/sample-vpc   True    True     vpc-0f8da654a40cb68cb   10m

NAME                                                          READY   SYNCED   EXTERNAL-NAME       AGE
securitygrouprule.ec2.aws.upbound.io/test-vpc-securitygroup   True    True     sgrule-2687506433   10m
```

### CODE REVIEW

**Comment by ytsarev** [comment]
/test-examples="examples/ec2/securitygrouprule-self-true.yaml"

File: config/ec2/config.go [hunk 1]
```diff
@@ -194,6 +194,11 @@ func Configure(p *config.Provider) {
 		r.References["source_security_group_id"] = config.Reference{
 			Type: "SecurityGroup",
 		}
+		r.LateInitializer = config.LateInitializer{
+			IgnoredFields: []string{
+				"self", "source_security_group_id",
```
Comment (ulucinar) [inline config/ec2/config.go:199]: [Should we also include](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule#self) `cidr_blocks` and `ipv6_cidr_blocks` together with the `source_security_group_id`? 

I guess they don't get late-initialized since we have already tested the new configuration and hence not included here. Is this correct?

File: examples/ec2/securitygrouprule-self-true.yaml [hunk 2]
```diff
@@ -0,0 +1,44 @@
+apiVersion: ec2.aws.upbound.io/v1beta1
```
Comment (ulucinar) [inline examples/ec2/securitygrouprule-self-true.yaml:1]: We had better add the `meta.upbound.io/example-id: ec2/v1beta1/securitygrouprule` annotations to the resource manifests.

**Review by ulucinar — APPROVED** [review]
Hi @ytsarev,
Thank you very much for the quick fix.

As a future work, we can discuss how to utilize the [schema.Schema.ConflictsWith](https://github.com/hashicorp/terraform-plugin-sdk/blob/2b557120cdae1e960aead54a299748a418ca3e94/helper/schema/schema.go#L269) to auto configure late initialization.
