### PR TITLE
(bugfix) Fix cognito user pool client orphaned resources

### LINKED ISSUE #807: Cognito UserPoolClient resource creation fails with internal operator error
### What happened?

Creating a Cognito UserPoolClient for a UserPool fails. The resource passes validation successfully when being applied, but the client is never created. When checking the status of the resource, I get the following result:  

```
apiVersion: v1
items:
- apiVersion: cognitoidp.aws.upbound.io/v1beta1
  kind: UserPoolClient
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cognitoidp.aws.upbound.io/v1beta1","kind":"UserPoolClient","metadata":{"annotations":{},"labels":{"msi.upbound.io/user-pool-client-name":"cp-msi-test-user-pool-client"},"name":"cp-msi-test-user-pool-client"},"spec":{"forProvider":{"allowedOauthFlowsUserPoolClient":true,"allowedOauthScopes":["email","openid","profile"],"callbackUrls":["http://localhost:8000"],"explicitAuthFlows":["ALLOW_REFRESH_TOKEN_AUTH","ALLOW_CUSTOM_AUTH","ALLOW_USER_SRP_AUTH"],"generateSecret":false,"idTokenValidity":1,"name":"cp-msi-test-user-pool-client","refreshTokenValidity":2,"region":"us-east-1","userPoolIdSelector":{"matchLabels":{"msi.upbound.io/userpool-name":"cp-msi-test"}}},"providerConfigRef":{"name":"msi-aws-dev"}}}
    creationTimestamp: "2023-08-02T18:06:35Z"
    generation: 3
    labels:
      msi.upbound.io/user-pool-client-name: cp-msi-test-user-pool-client
    name: cp-msi-test-user-pool-client
    resourceVersion: "77568032"
    uid: 72ac8279-8b72-4974-9463-f31f136d89ac
  spec:
    deletionPolicy: Delete
    forProvider:
      allowedOauthFlowsUserPoolClient: true
      allowedOauthScopes:
      - email
      - openid
      - profile
      callbackUrls:
      - http://localhost:8000
      explicitAuthFlows:
      - ALLOW_REFRESH_TOKEN_AUTH
      - ALLOW_CUSTOM_AUTH
      - ALLOW_USER_SRP_AUTH
      generateSecret: false
      idTokenValidity: 1
      name: cp-msi-test-user-pool-client
      refreshTokenValidity: 2
      region: us-east-1
      userPoolId: us-east-1_S4gvrPh9H
      userPoolIdRef:
        name: cp-msi-test
      userPoolIdSelector:
        matchLabels:
          msi.upbound.io/userpool-name: cp-msi-test
    managementPolicy: FullControl
    providerConfigRef:
      name: msi-aws-dev
  status:
    atProvider: {}
    conditions:
    - lastTransitionTime: "2023-08-02T18:07:28Z"
      message: |
        observe failed: cannot run refresh: refresh failed: reading Amazon Cognito IDP (Identity Provider) User Pool Client (): InvalidParameter: 1 validation error(s) found.
        - minimum field size of 1, DescribeUserPoolClientInput.ClientId.
      reason: ReconcileError
      status: "False"
      type: Synced
kind: List
metadata:
  resourceVersion: ""
```

### How can we reproduce it?

Create a UserPool:  

```
apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPool
metadata:
  labels:
    test.upbound.io/userpool-name: my-user-pool
  name: my-user-pool
spec:
  forProvider:
    name: my-user-pool
    autoVerifiedAttributes:
    - email
    usernameAttributes:
    - email
    passwordPolicy:
    - minimumLength: 6
      requireNumbers: false
      requireSymbols: false
      requireUppercase: false
      requireLowercase: false
    region: us-east-1
  providerConfigRef:
    name: my-aws-provider
```

Then create the UserPoolClient:

```
apiVersion: cognitoidp.aws.upbound.io/v1beta1
kind: UserPoolClient
metadata:
  labels:
    test.upbound.io/user-pool-client-name: my-user-pool-client
  name: my-user-pool-client
spec:
  forProvider:
    name: my-user-pool-client
    region: us-east-1
    userPoolIdSelector:
      matchLabels:
        test.upbound.io/userpool-name: my-user-pool
    explicitAuthFlows:
    - ALLOW_REFRESH_TOKEN_AUTH
    - ALLOW_CUSTOM_AUTH
    - ALLOW_USER_SRP_AUTH
    generateSecret: false
    callbackUrls:
    - http://localhost:8000
    allowedOauthFlowsUserPoolClient: true
    allowedOauthScopes:
    - email
    - openid
    - profile
    refreshTokenValidity: 2
    idTokenValidity: 1
  providerConfigRef:
    name: my-aws-provider
```

Then check UserPoolStatus:

```
kubectl describe userpoolclient my-user-pool-client
```

Which prints the error mentioned in the problem description above.

When checking the AWS console for the UserPool, the UserPoolClient is never created.

### What environment did it happen in?

* Crossplane Version: 1.13.1
* Provider Version: upbound/provider-aws-cognitoidp@v0.36.0
* Kubernetes Version: v1.25.4
* Kubernetes Distribution: GKE - v1.25.10-gke.1200

### LINKED ISSUE #828: CognitoIDP[UserPoolClient]: UserPoolClient name has unexpected validation errors when contains uppercase / non word characters
### What happened?

As a side effect of [762](https://github.com/upbound/provider-aws/pull/762), the UserPoolClient name now throws a validation error when the name contains any special characters like `-` or `.`. Client Name doesn't have such restrictions according to [AWS Docs](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#CognitoUserPools-CreateUserPoolClient-request-ClientName)

The validation rules of Client ID [[\w+]+](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DescribeUserPoolClient.html#API_DescribeUserPoolClient_RequestSyntax), now applies on top of validation rules of Client Name.

### How can we reproduce it?

Create a user pool client with name`org-name`, This will error out with:

```
observe failed: cannot run refresh: refresh failed: reading Amazon
        Cognito IDP (Identity Provider) User Pool Client (org-name):
        InvalidParameterException: 1 validation error detected: Value
        'org-name` at 'clientId' failed to satisfy constraint: Member must
        satisfy regular expression pattern: [\w+]+
```

### What environment did it happen in?

* Crossplane Version: [v1.10.4](https://github.com/crossplane/crossplane/releases/tag/v1.10.4)
* Provider Version: [v0.38.0](https://github.com/upbound/provider-aws/releases/tag/v0.38.0)
* Kubernetes Version: v1.23.17
* Kubernetes Distribution: EKS

### LINKED ISSUE #1049: Cognito UserPoolClient becomes Synced: false or creates duplicate AWS resources when provider pod restarts
### What happened?
I have existing UserPoolClient.cognitoidp resources in my cluster, which were created before the changes in #762. 

They have a `spec.forProvider.name` that contains a `-`. 

When my provider pods restart, my managed resources get a condition like:
```
  - lastTransitionTime: "2023-12-30T22:35:34Z"
    message: 'observe failed: cannot run refresh: refresh failed: reading Amazon Cognito
      IDP (Identity Provider) User Pool Client (example-resource):
      InvalidParameterException: 1 validation error detected: Value ''my-client-name''
      at ''clientId'' failed to satisfy constraint: Member must satisfy regular expression
      pattern: [\w+]+'
    reason: ReconcileError
    status: "False"
    type: Synced
```

I can get them back to `Synced: True` if I `exec` into the pod and manually edit the `id` value in the `terraform.tfstate` file to match the id of the user pool client, which is correctly persisted in the external name annotation and in `status.atProvider.id`. Note that this is one of the handful of resources still using the CLI-based reconciler.

As demonstrated in #762, if my `spec.forProvider.name` matched the client id regex, then crossplane would create a second user pool client in aws.

### How can we reproduce it?

See https://github.com/upbound/provider-aws/pull/1048

### What environment did it happen in?

* Crossplane Version: 
* Provider Version:
* Kubernetes Version:  
* Kubernetes Distribution:

### PR DESCRIPTION
**Pull request by mbbush**
### Description of your changes

The cognito idp user pool client is one of the handful of resources in terraform-provider-aws v4.67.0 that use the terraform plugin framework, and therefore that we still reconcile by forking a CLI terraform process. 

There are three problems with the cognito user pool client:
1. Creation fails if the `spec.forProvider.name` doesn't match the regex for the `clientId`
2. Whenever the provider pod restarts, crossplane will either create a duplicate resource, orphaning the existing one, or get into a Synced: False state, depending on whether `spec.forProvider.name` matches the `clientId` regex. 
3. Observe-only resources fail, because `terraform import` expects an argument that is not the same as the terraform id. 

This PR fixes the first two issues, and makes the third issue no worse. 

### Context

This resource has two idiosyncrasies that make it difficult. 

1. Calling `terraform apply -refresh-only` with an id of `""` returns an error, because the terraform provider passes through the empty-string id to the aws sdk, which (correctly) complains that trying to find a user pool client with id `""` is invalid. I suspect this is *because* the resource uses the terraform plugin framework, which introduced the concept of a null value as distinct from a zero value. I suspect that if we had some way to specify a null value for the id, it would work fine, but the type in upjet is `string` not `*string` so I don't see how to do that without major changes. Maybe the upjet developers will need to add a transformation layer from zero values back to null when integrating with the terraform provider framework, or perhaps they'll come up with a better idea. 

2. The argument needed to `terraform import` the resource is different than the terraform id, but the terraform id is needed to run `terraform apply -refresh-only`. The provider uses `terraform import` for resources with management policy `Observe` and `terraform apply -refresh-only` for other management policies. Unless someone has a clever way to identify which case we're in, in the context of an external name configuration, we can only support one of these use cases.

#762 was an attempt to work around the `"id":""` issue, but it introduced new problems.

My solution for the first issue is to simply use a static client id of "invalidnonemptystring", which satisfies the client id regex `[\w+]+`, so doesn't cause an error when we run `terraform apply -refresh-only`, but also doesn't match any actual existing client id (the aws-generated ids that I've seen are all 26 lowercase alphanumeric characters long). This feels like getting the right result by doing the wrong thing, but I can't think of any actual problems it would cause, nor can I come up with a better idea. 

For the second issue, I've chosen to write an external name config that supports assuming full control of existing resources, and does not support observing existing resources only, as that seems like the lesser of two evils (especially since it's necessary for recovering from a provider pod crash restart). It also has the advantage of keeping the terraform id set to the value of the terraform id (except when we don't have an id, so set it to `"invalidnonemptystring"` to get the necessary NotFound response). 

Ultimately I hope that when we reconcile this through the terraform plugin framework, we'll be able to ignore the format expected by `terraform import` and just use the id and user pool id parameters. It looks like that's exactly the implementation used in the `Read` method on the terraform provider. 

Fixes #828 
Fixes #807 
Fixes #1049 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Uptest passes. It did not pass on `main` with the previous config, because the import step resulted in creating a second user pool client. 

Creating an observe-only resource fails. This is not a regression, as it fails in the same way with the current version of the provider, and I don't believe it is fixable without breaking other, more important functionality.

The external name format is remaining the same: the alphanumeric client id. 

When I ran uptest locally for the existing `examples/cognitoidp/userpooluicustomization.yaml`, I got an error about the domain already being registered, so I updated the example to use a random domain name and now it passes consistently.

### CODE REVIEW

**Comment by mbbush** [comment]
/test-examples="examples/cognitoidp/userpoolclient.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/cognitoidp/userpooluicustomization.yaml"

File: config/externalname.go [hunk 1]
```diff
@@ -2659,14 +2659,38 @@ var CLIReconciledExternalNameConfigs = map[string]config.ExternalName{
...
+// Note(mbbush) This resource has some unexpected behaviors that make it impossible to write a completely correct
+// ExternalName config. Specifically, the terraform id returned in the terraform state is not the same as the
+// identifier used to import it. Additionally, if the terraform id set to an empty string, the terraform
+// provider passes the empty string through to the aws query during refresh, which returns an api error.
+// This could be related to the fact that this resource is implemented using the terraform plugin framework,
+// which introduces the concept of a null value as distinct from a zero value.
+func cognitoUserPoolClient() config.ExternalName {
+	e := config.IdentifierFromProvider
+	// TODO: Uncomment when it's acceptable to remove fields from spec.initProvider (major release)
+	//e.IdentifierFields = []string{"user_pool_id"}
```
Comment (mbbush) [inline config/externalname.go:2681]: Before I rebased and included https://github.com/upbound/provider-aws/pull/1046, setting this was a non-breaking change, since reference fields and identifier fields were both omitted from `spec.initProvider`. Now, if I set it here, then upjet removes `userPoolId`, `userPoolIdRef` and `userPoolIdSelector` from `spec.initProvider`. 

For this resource, not having those fields in `initProvider` seems totally fine (if they change, terraform will require destroying and recreating the resource anyways), and it is necessary to know the user pool id in some form in order to read the state of the resource from AWS, so it seems to conceptually fit as an identifier field. 

This is a bugfix, so I think the best compromise is to leave it commented out, with a TODO to add it back when we do a major release.

**Comment by mbbush** [comment]
/test-examples="examples/cognitoidp/userpoolclient-with-dashes.yaml, examples/cognitoidp/userpoolclient-observe.yaml"

**Comment by mbbush** [comment]
/test-examples="examples/cognitoidp/userpoolclient.yaml, examples/cognitoidp/userpoolclient-with-dashes.yaml"

**Comment by mbbush** [comment]
@ulucinar @turkenf @sergenyalcin I'd really like to get this merged and (ideally) released promptly. This resource is basically unusable without this fix.

**Comment by turkenf** [comment]
/test-examples="examples/cognitoidp/userpoolclient.yam

**Comment by turkenf** [comment]
/test-examples="examples/cognitoidp/userpoolclient.yaml"

**Comment by turkenf** [comment]
/test-examples="examples/cognitoidp/userpoolclient-with-dashes.yaml"

**Review by turkenf — COMMENTED** [review]
Thank you for this PR @mbbush, I left a few comments to you for consider.

**Review by turkenf — APPROVED** [review]
Thank you for your work on this PR @mbbush, the improvements noted in the comments above are not prohibitive in moving this PR forward and can be fixed later.

**Review by ulucinar — APPROVED** [review]
Thank you @mbbush, lgtm.
