### PR TITLE
Add configurations of datasync (1), directory_service (4), dms (1), dx (1), dynamodb (1), ec2 (4), efs (1), emrserverless (1), evidently (3), fis (1), fix (1), glue (1), grafana (1), identitystore (3), inspector2 (3), ivs (3) groups

### LINKED ISSUE #471: Configure datasync (1), directory_service (4), dms (1), dx (1), dynamodb (1), ec2 (4), efs (1), emrserverless (1), evidently (3), fis (1), fix (1), glue (1), grafana (1), identitystore (3), inspector2 (3), ivs (3)
Configure external name without testing:

* `datasync`
  * [x] [aws_datasync_location_object_storage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_location_object_storage)

* `directory_service`
  * [x] [aws_directory_service_radius_settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_radius_settings)
  * [x] [aws_directory_service_region](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_region)
  * [x] [aws_directory_service_shared_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory)
  * [x] [aws_directory_service_shared_directory_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory_accepter)

* `dms`
  * [x] [aws_dms_s3_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_s3_endpoint)

* `dx`
  * [x] [aws_dx_macsec_key_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_macsec_key_association)

* `dynamodb`
  * [x] [aws_dynamodb_table_replica](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_replica)

* `ec2`
  * [x] [aws_ec2_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_instance_state)
  * [x] [aws_ec2_network_insights_analysis](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_analysis)
  * [x] [aws_ec2_transit_gateway_policy_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table)
  * [x] [aws_ec2_transit_gateway_policy_table_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table_association)

* `efs`
  * [x] [aws_efs_replication_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_replication_configuration)

* `emrserverless`
  * [x] [aws_emrserverless_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrserverless_application)

* `evidently`
  * [x] [aws_evidently_feature](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_feature)
  * [x] [aws_evidently_project](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_project)
  * [x] [aws_evidently_segment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_segment)

* `fis`
  * [x] [aws_fis_experiment_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template)

* `fsx`
  * [x] [aws_fsx_file_cache](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_file_cache)

* `glue`
  * [x] [aws_glue_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_schema)

* `grafana`
  * [x] [aws_grafana_workspace_api_key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace_api_key)

* `identitystore`
  * [x] [aws_identitystore_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group)
  * [x] [aws_identitystore_group_membership](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group_membership)
  * [x] [aws_identitystore_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_user)

* `inspector2`
  * [x] [aws_inspector2_delegated_admin_account](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_delegated_admin_account)
  * [x] [aws_inspector2_enabler](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_enabler)
  * [x] [aws_inspector2_organization_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_organization_configuration)

* `ivs`
  * [x] [aws_ivs_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_channel)
  * [x] [aws_ivs_playback_key_pair](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_playback_key_pair)
  * [x] [aws_ivs_recording_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_recording_configuration)

### PR DESCRIPTION
**Pull request by dverveiko**
### Description of your changes
Add external name configuration without testing:

* `datasync`
  * [x] [aws_datasync_location_object_storage](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_location_object_storage)

* `directory_service`
  * [x] [aws_directory_service_radius_settings](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_radius_settings)
  * [x] [aws_directory_service_region](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_region)
  * [x] [aws_directory_service_shared_directory](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory)
  * [x] [aws_directory_service_shared_directory_accepter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/directory_service_shared_directory_accepter)

* `dms`
  * [x] [aws_dms_s3_endpoint](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dms_s3_endpoint)

* `dx`
  * [x] [aws_dx_macsec_key_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dx_macsec_key_association)

* `dynamodb`
  * [x] [aws_dynamodb_table_replica](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table_replica)

* `ec2`
  * [x] [aws_ec2_instance_state](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_instance_state)
  * [x] [aws_ec2_network_insights_analysis](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_network_insights_analysis)
  * [x] [aws_ec2_transit_gateway_policy_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table)
  * [x] [aws_ec2_transit_gateway_policy_table_association](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_transit_gateway_policy_table_association)

* `efs`
  * [x] [aws_efs_replication_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/efs_replication_configuration)

* `emrserverless`
  * [x] [aws_emrserverless_application](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emrserverless_application)

* `evidently`
  * [x] [aws_evidently_feature](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_feature)
  * [x] [aws_evidently_project](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_project)
  * [x] [aws_evidently_segment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/evidently_segment)

* `fis`
  * [x] [aws_fis_experiment_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fis_experiment_template)

* `fsx`
  * [x] [aws_fsx_file_cache](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/fsx_file_cache)

* `glue`
  * [x] [aws_glue_schema](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_schema)

* `grafana`
  * [x] [aws_grafana_workspace_api_key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/grafana_workspace_api_key)

* `identitystore`
  * [x] [aws_identitystore_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group)
  * [x] [aws_identitystore_group_membership](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_group_membership)
  * [x] [aws_identitystore_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_user)

* `inspector2`
  * [x] [aws_inspector2_delegated_admin_account](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_delegated_admin_account)
  * [x] [aws_inspector2_enabler](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_enabler)
  * [x] [aws_inspector2_organization_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector2_organization_configuration)

* `ivs`
  * [x] [aws_ivs_channel](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_channel)
  * [x] [aws_ivs_playback_key_pair](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_playback_key_pair)
  * [x] [aws_ivs_recording_configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ivs_recording_configuration)

Fixes #471 

I have:

- [x] Run `make reviewable test` to ensure this PR is ready for review.

### CODE REVIEW

File: config/externalnamenottested.go [hunk 1]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	"aws_emrserverless_application": config.IdentifierFromProvider,
+
+	// evidently
+	//
+	// CloudWatch Evidently Feature can be imported using the feature name and name or arn of the hosting CloudWatch Evidently Project separated by a :
+	// Example: exampleFeatureName:arn:aws:evidently:us-east-1:123456789012:project/example
+	"aws_evidently_feature": config.TemplatedStringAsIdentifier("name", "{{ .external_name }}:{{ .parameters.project }}"),
+	// CloudWatch Evidently Project can be imported using the arn
+	// Example: arn:aws:evidently:us-east-1:123456789012:segment/example
+	"aws_evidently_project": config.TemplatedStringAsIdentifier("name", "arn:aws:evidently:{{ .setup.configuration.region }}:{{ .setup.client_metadata.account_id }}:segment/{{ .external_name }}"),
```
Comment (ulucinar) [inline config/externalnamenottested.go:655]: I think the Terraform docs contain a typo here:
```suggestion
	"aws_evidently_project": config.TemplatedStringAsIdentifier("name", "arn:aws:evidently:{{ .setup.configuration.region }}:{{ .setup.client_metadata.account_id }}:project/{{ .external_name }}"),
```

Let's also add a TODO so that we are extra careful while testing this.

File: config/externalnamenottested.go [hunk 2]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// CloudWatch Evidently Segment can be imported using the arn
+	// Example: arn:aws:evidently:us-west-2:123456789012:segment/example
+	"aws_evidently_segment": config.TemplatedStringAsIdentifier("name", "arn:aws:evidently:{{ .setup.configuration.region }}:{{ .setup.client_metadata.account_id }}:segment/{{ .external_name }}"),
```
Comment (ulucinar) [inline config/externalnamenottested.go:658]: A general comment:
We should prefer the `spec.forProvider.region` (if the managed resource contains it. e.g., MR is a non-IAM resource) in place of the region from the provider configuration block. Because the two could in theory differ from each other and the region to which the resource belongs is determined by `spec.forProvider.region`:
```suggestion
	"aws_evidently_segment": config.TemplatedStringAsIdentifier("name", "arn:aws:evidently:{{ .parameters.region }}:{{ .setup.client_metadata.account_id }}:segment/{{ .external_name }}"),
```

File: config/externalnamenottested.go [hunk 3]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// fsx
+	//
+	// Amazon File Cache cache can be imported using the resource id
+	"aws_fsx_file_cache": config.IdentifierFromProvider,
+
+	// glue
+	//
+	// Glue Registries can be imported using arn
+	// Example: arn:aws:glue:us-west-2:123456789012:schema/example/example
+	"aws_glue_schema": config.TemplatedStringAsIdentifier("schema_name", "{{ .parameters.registry_arn }}/{{ .external_name }}"),
```
Comment (ulucinar) [inline config/externalnamenottested.go:674]: Checked the example ARN given for the `aws_glue_registry` resource: `arn:aws:glue:us-west-2:123456789012:registry/example`

This does not match the example ARN given for the `aws_glue_schema` resource (it's not a prefix of that example).

But what we have here looks correct. Let's add a TODO (so that we will remember while doing the tests).

File: config/externalnamenottested.go [hunk 4]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// grafana
+	//
+	// No import
+	// TODO: For now API is not normalized. While testing resource we can check the actual ID and normalize the API.
+	"aws_grafana_workspace_api_key": config.IdentifierFromProvider,
+
+	// identitystore
+	//
+	// An Identity Store Group can be imported using the combination identity_store_id/group_id
+	"aws_identitystore_group": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:685]: We can normalize the external-name so that it's just the (provider-assigned) `group_id` with something like:
```suggestion
	"aws_identitystore_group": config.TemplatedStringAsIdentifier("", "{{ .parameters.identity_store_id }}/{{ .external_name }}"),
```

File: config/externalnamenottested.go [hunk 5]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// aws_identitystore_group_membership can be imported using the identity_store_id/membership_id
+	"aws_identitystore_group_membership": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:687]: We can normalize the external-name so that it's just the (provider-assigned) `membership_id` with something like:
```suggestion
	"aws_identitystore_group_membership": config.TemplatedStringAsIdentifier("", "{{ .parameters.identity_store_id }}/{{ .external_name }}"),
```

File: config/externalnamenottested.go [hunk 6]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// An Identity Store User can be imported using the combination identity_store_id/user_id
+	"aws_identitystore_user": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:689]: We can normalize the external-name so that it's just the (provider-assigned) `user_id` with something like:
```suggestion
	"aws_identitystore_user": config.TemplatedStringAsIdentifier("", "{{ .parameters.identity_store_id }}/{{ .external_name }}"),
```

File: config/externalnamenottested.go [hunk 7]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+
+	// inspector2
+	//
+	// Inspector V2 Delegated Admin Account can be imported using the account_id
+	"aws_inspector2_delegated_admin_account": config.ParameterAsIdentifier("account_id"),
```
Comment (ulucinar) [inline config/externalnamenottested.go:694]: The provided example ID (for `account_id`) is not a valid DNS subdomain name. So, if users of this API try to specify the `account_id` via `metadata.name` (starting with a number), it will fail. 

Although users of the API can overcome this technical limitation by specifying the `account_id` via the external-name annotation, I will suggest not to use the `metadata.name` to specify the `account_id`. I suggest using `config.IdentifierFromProvider` here although we sacrifice some XRM adherence because I _believe_ it will serve a better UX.

File: config/externalnamenottested.go [hunk 8]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// No import
+	// TODO: For now API is not normalized. While testing resource we can check the actual ID and normalize the API.
+	"aws_inspector2_enabler": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:697]: Not sure if we will be able to test this resource:
image

:)) 

Let's add a comment here so that we do not spend too much time on testing this. What do you think?

File: config/externalnamenottested.go [hunk 9]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// No import
+	// TODO: For now API is not normalized. While testing resource we can check the actual ID and normalize the API.
+	"aws_inspector2_organization_configuration": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:700]: We may need to split this resource and mark it as a resource whose testing requires some sort of priveleges:
image

Let's add a TODO here to make a note of this.

File: config/externalnamenottested.go [hunk 10]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+
+	// ivs
+	//
+	// IVS (Interactive Video) Channel can be imported using the ARN
+	// Example: arn:aws:ivs:us-west-2:326937407773:channel/0Y1lcs4U7jk5
+	"aws_ivs_channel": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:706]: We can just leave the last path component in ARN for the external-name annotation with `config.TemplatedStringAsIdentifier` (for normalization).

File: config/externalnamenottested.go [hunk 11]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// IVS (Interactive Video) Playback Key Pair can be imported using the ARN
+	// Example: arn:aws:ivs:us-west-2:326937407773:playback-key/KDJRJNQhiQzA
+	"aws_ivs_playback_key_pair": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:709]: We can just leave the last path component in ARN for the external-name annotation with `config.TemplatedStringAsIdentifier`  (for normalization).

File: config/externalnamenottested.go [hunk 12]
```diff
@@ -590,4 +590,124 @@ var ExternalNameNotTestedConfigs = map[string]config.ExternalName{
...
+	// IVS (Interactive Video) Recording Configuration can be imported using the ARN
+	// Example: arn:aws:ivs:us-west-2:326937407773:recording-configuration/KAk1sHBl2L47
+	"aws_ivs_recording_configuration": config.IdentifierFromProvider,
```
Comment (ulucinar) [inline config/externalnamenottested.go:712]: We can just leave the last path component in ARN for the external-name annotation with `config.TemplatedStringAsIdentifier` (for normalization).

**Review by ulucinar — COMMENTED** [review]
Thank you @dverveiko for configuring these resources. Left some comments for discussion.

**Review by ulucinar — APPROVED** [review]
Thank you @dverveiko, lgtm.
